version: '3.8'

services:
  # Banco de Dados Profissional (PostgreSQL)
  postgres-db:
    image: postgres:15
    container_name: postgres_music
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpassword
      POSTGRES_DB: musicdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Armazenamento de Imagens (MinIO)
  minio:
    image: minio/minio
    container_name: minio_music
    ports:
      - "9000:9000" # Porta da API (S3)
      - "9001:9001" # Porta do Console (Browser)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: