services:
  # Banco de Dados
  postgres-db:
    image: postgres:15
    container_name: postgres_music
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpassword
      POSTGRES_DB: musicdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicuser -d musicdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Armazenamento S3
  minio:
    image: minio/minio
    container_name: minio_music
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  # Sua API Spring Boot
  api-music:
    build: .
    container_name: spring_api_music
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

# ESSA SEÇÃO ABAIXO ERA O QUE ESTAVA FALTANDO:
volumes:
  postgres_data:
  minio_data: