# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/musicdb
spring.datasource.username=musicuser
spring.datasource.password=musicpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=album-covers

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Garante que o Hibernate não tente criar as tabelas (deixe o Flyway fazer isso)
spring.jpa.hibernate.ddl-auto=validate

# Expor os endpoints do Actuator
management.endpoints.web.exposure.include=health,info

# Habilitar grupos específicos de Liveness e Readiness
management.endpoint.health.probes.enabled=true

# Mostrar detalhes dos componentes (banco, minio, etc)
management.endpoint.health.show-details=always