spring.application.name=music-api
spring.datasource.url=jdbc:h2:mem:musicdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=album-covers
